### ISSUE TITLE
Missing MAUTIC_TABLE_PREFIX

### ISSUE THREAD

**Issue by djpmedia** [TheDMSGroup/mautic-contact-ledger#97]
This gives an sql error by the campains.
https://github.com/TheDMSGroup/mautic-contact-ledger/blob/3b6b586c33e792be6ec08e4cd7b420c6660c1a7a/Entity/LedgerEntryRepository.php#L86

**Comment by heathdutton** [comment]
Mind putting in a pr?

**Comment by djpmedia** [comment]
> Mind putting in a pr?

I've added a pull request
